/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BrowserWindow: typeof import('./src/components/BrowserWindow.vue')['default']
    Features: typeof import('./src/components/Features.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    KeyShortcut: typeof import('./src/components/KeyShortcut.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
